**VETORES**

Os vetores e as matrizes estruturas de dados estáticas e que suportam um tipo de dado. Quando criamos um vetor numpy vazio, por padrão, é criado o tipo float. Uma vez definido seu tamanho, não é mais possível alterar. São acessados também por indices que iniciam em zero(0), ocupam menos que as listas e são mais rápidos também. Para criá-lo é necessário importar a biblioteca numpy.


In [1]:
import numpy as np

vetor1 = np.array([1,2,3,4,5]) #cria um vetor de inteiros

In [2]:
type(vetor1)

numpy.ndarray

In [3]:
vetor1.dtype #mostra o tipo do vetor

dtype('int64')

In [4]:
vetor2 = np.array([2.5, 3.8, 5.9]) #cria um vetor float

In [5]:
vetor2.dtype

dtype('float64')

In [6]:
vetor3 = np.array(['Ana', 'Marcelo', 'Gustavo']) #cria um vetor de string

In [7]:
vetor3.dtype

dtype('<U7')

In [10]:
vet1 = np.array([1,2,3])
vet2 = np.array([4,5,6])

In [11]:
#ALGUMAS OPERAÇÕES ARITMÉTICAS COM VETORES

vet1 + vet2 #soma os elementos dos dois vetores

array([5, 7, 9])

In [12]:
print(vet1 * 2) #multiplica os elementos por 2

[2 4 6]


In [13]:
vet1

array([1, 2, 3])

In [14]:
vet1[1] = 50 #sobrepõe o valor da posição

In [15]:
vet1

array([ 1, 50,  3])

In [16]:
vet1.sort() #coloca o vetor em ordem crescente

In [17]:
vet1

array([ 1,  3, 50])

In [18]:
del vet1 #apaga o vetor inteiro da memória

In [19]:
#CRIAR UM VETOR COM ARANGE()

vetor = np.arange(10) #cria um vetor com 10 números consecutivos

In [20]:
vetor

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#CRIAR UM VETOR COM NÙMEROS ALEATÓRIOS

import random

vetor2 = np.random.randint(100, size=(10)) #cria um vetor com 10 números aleatórios na faixa de 0 a 100

In [25]:
vetor2

array([21, 36, 54, 56, 69, 12, 98, 71, 48, 19])

In [26]:
#ALGUMAS FUNÇÕES DOS VETORES 

np.max(vetor2) #retorna o maior do vetor

98

In [27]:
np.min(vetor2) #retorna o menor do vetor

12

In [28]:
np.mean(vetor2) #retorna a média dos valores do vetor

48.4

In [29]:
np.sum(vetor2) #retorna a soma dos valores do vetor

484

In [30]:
#PARA CRIAR UM VETOR VAZIO 

vetor3 = np.empty(5) #cria um vetor vazio com 5 posições

In [31]:
vetor3

array([1., 1., 1., 1., 1.])

In [32]:
vetor3[0] = 89
vetor3[1] = 18
vetor3[2] = 36
vetor3[3] = 12
vetor3[4] = 65

In [33]:
vetor3

array([89., 18., 36., 12., 65.])

In [34]:
#CARREGANDO UM VETOR PELO TECLADO

valores = np.empty(5)
for i in range(5):
  valores[i] = input('Número: ')

print(valores)

Número: 4
Número: 54
Número: 23
Número: 76
Número: 34
[ 4. 54. 23. 76. 34.]


**MATRIZES**

In [35]:
matriz = np.array([[1,2,3],[4,5,6]])

In [36]:
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
matriz.shape # retorna a dimensão da matriz

(2, 3)

In [38]:
matriz[0,1] #retorna o valor da linha 0 e coluna 1

2

**CRIANDO MATRIZES ESPECÍFICAS**

In [39]:
#MATRIZ IDENTIDADE

I = np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [40]:
#MATRIZ DIAGONAL

D = np.diag(np.arange(5))
print(D)

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]


In [41]:
#MATRIZ DE ZEROS

Z = np.zeros([3,3])
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [42]:
#MATRIZ DE UNS

U = np.ones([3,3])
print(U)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [43]:
#GERANDO UMA MATRIZ COM NÚMEROS ALEATÓRIOS

matriz = np.random.randint(100, size=(2,3))
print(matriz)

[[80 41 51]
 [76 53 94]]
